[phases.setup]
nixPkgs = ['nodejs', 'npm']

[phases.install]
cmds = ['cd server && npm install']

[phases.build]
cmds = ['echo "Backend server - no build step required"']

[start]
cmd = 'cd server && npm start' 